version: "3.4"

services:

  eureka-server:
    build:
      context: ./bookstore-eureka-discovery-service
      args:
        JAR_FILE: bookstore-eureka-discovery-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=8761

  gateway-server:
    build:
      context: ./bookstore-api-gateway-service
      args:
        JAR_FILE: bookstore-api-gateway-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: gateway-server
    ports:
      - "8765:8765"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=8765
      - EUREKA_HOST=eureka-server:8761
      - ZIPKIN_HOST=zipkin-server:9411
    depends_on:
      - eureka-server

  account-service:
    build:
      context: ./bookstore-account-service
      args:
        JAR_FILE: bookstore-account-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: account-service
    ports:
      - "4001:4001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=4001
      - EUREKA_HOST=eureka-server:8761
      - ZIPKIN_HOST=zipkin-server:9411
    depends_on:
      - gateway-server
      - eureka-server

  billing-service:
    build:
      context: ./bookstore-billing-service
      args:
        JAR_FILE: bookstore-billing-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: billing-service
    ports:
      - "5001:5001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=5001
      - EUREKA_HOST=eureka-server:8761
      - ZIPKIN_HOST=zipkin-server:9411
    depends_on:
      - gateway-server
      - eureka-server

  catalog-service:
    build:
      context: ./bookstore-catalog-service
      args:
        JAR_FILE: bookstore-catalog-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: catalog-service
    ports:
      - "6001:6001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=6001
      - EUREKA_HOST=eureka-server:8761
      - ZIPKIN_HOST=zipkin-server:9411
    depends_on:
      - gateway-server
      - eureka-server

  order-service:
    build:
      context: ./bookstore-order-service
      args:
        JAR_FILE: bookstore-order-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: order-service
    ports:
      - "7001:7001"
    networks:
      - bookstore-app-network
    environment:
      - SERVER_PORT=7001
      - EUREKA_HOST=eureka-server:8761
      - ZIPKIN_HOST=zipkin-server:9411
    depends_on:
      - gateway-server
      - eureka-server

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    hostname: zipkin-host
    ports:
      - "9411:9411"
    networks:
      - bookstore-app-network

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    networks:
      - bookstore-app-network

  grafana:
    image: "grafana/grafana"
    ports:
      - "3030:3000"
    container_name: grafana
    networks:
      - bookstore-app-network

networks:
  bookstore-app-network:
    driver: bridge