server:
  port: ${SERVER_PORT:5001}

spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
    enabled: true
    service:
      name: bookstore-order-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
#    schema: classpath:sql-scripts/schema.sql
#    data: classpath:sql-scripts/data.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    registerWithEureka: true
  instance:
    prefer-ip-address: false

logging.level.com.lmi.spring: DEBUG

hystrix:
  metrics:
    enabled: true
feign:
  hystrix:
    enabled: true

management:
  endpoint:
    hystrix:
      stream:
        enabled: true