server:
  port: ${SERVER_PORT:6001}

spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
    enabled: true
    service:
      name: bookstore-catalog-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    registerWithEureka: true
  instance:
    prefer-ip-address: false

logging.level.com.lmi.spring: DEBUG

