server:
  port: ${SERVER_PORT:8765}

spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
    enabled: true
    service:
      name: bookstore-api-gateway-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0

zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 20000
  prefix: /api
  routes:
    address:
      path: /address/**
      serviceId: address-service
    users:
      path: /users/**
      serviceId: users-service
  ribbon:
    eager-load:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    registerWithEureka: true
  instance:
    prefer-ip-address: false