server:
  port: ${SERVER_PORT:8765}

spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
    enabled: true
    service:
      name: bookstore-api-gateway-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 20000
    connection-request-timeout-millis: 10000
  prefix: /api
  routes:
    address:
      path: /catalog/**
      serviceId: bookstore-catalog-service
    users:
      path: /billing/**
      serviceId: bookstore-billing-service
  ribbon:
    eager-load:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    registerWithEureka: true
  instance:
    prefer-ip-address: false

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000