server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
  instance:
    prefer-ip-address: false

#Excluding influx auto config, because we are not sending eureka metrics to influx.
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.influx.InfluxDbAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.influx.InfluxDbHealthIndicatorAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.export.influx.InfluxMetricsExportAutoConfiguration