server:
  port: ${SERVER_PORT:9009}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
    enabled: true
    service:
      name: bookstore-billing-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    registerWithEureka: true
  instance:
    prefer-ip-address: false

logging.level.com.devd.spring.*: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

#hystrix:
#  metrics:
#    enabled: true
#feign:
#  hystrix:
#    enabled: true

management:
  endpoint:
    hystrix:
      stream:
        enabled: true
#logging:
#  level: debug

